CREATE TABLE IF NOT EXISTS agent_content_publications (
  document_id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  content_json MEDIUMTEXT NOT NULL,
  version BIGINT UNSIGNED NOT NULL,
  published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
